### ISSUE TITLE
ANY(variable) can not be applied on REAL

### ISSUE THREAD

**Issue by QuentinRodier** [SebastienRietteMTO/PHYEX-fortran-tool#10]
reDimKlonArrayToScalar removes horizontal dimensions on purely horizonal variables.
Then, 1D/2D variables become real and ANY(real) is forbidden.

reDimKlonArrayToScalar must transform ANY(var) if var is transformed as a real.
Example : mode_ice4_sedimentation_split.F90

**Comment by SebastienRietteMTO** [comment]
Moved in https://github.com/UMR-CNRM/pyft/issues/4
