### ISSUE TITLE
addModuleVariable does not check if module is already used

### ISSUE THREAD

**Issue by QuentinRodier** [SebastienRietteMTO/PHYEX-fortran-tool#12]
The --addModuleVariable does not check if the module is already present in the locality.
It adds the USE MODULE statement by appending to existing module so if it is already present, it may cause troubles.

**Comment by QuentinRodier** [comment]
Is this really a problem ? To be tested with multiple USE of the same module

**Comment by SebastienRietteMTO** [comment]
Moved in https://github.com/UMR-CNRM/pyft/issues/5
