### ISSUE TITLE
ANY() and COUNT()

### ISSUE THREAD

**Issue by QuentinRodier** [SebastienRietteMTO/PHYEX-fortran-tool#14]
On PHYEX repo, branch demo-dwarf, commits :
https://github.com/UMR-CNRM/PHYEX/commit/6f801ec3d537e18e72a87d26137109309194240b
https://github.com/UMR-CNRM/PHYEX/commit/ef6b29a2517ba40ecf7f2c4a8a962baea35e7318
https://github.com/UMR-CNRM/PHYEX/commit/c6e9033a4802348c830c21283a1347ad4c9c1a71

transforms by hand COUNT() and ANY() in the case of the argument is a scalar.
(on master branch, CPU, arguments are arrays)

ANY and COUNT could be handle by PFT

**Comment by SebastienRietteMTO** [comment]
Moved in https://github.com/UMR-CNRM/pyft/issues/7
