### ISSUE TITLE
[Important Feature] Add the concept of tree 

### ISSUE THREAD

**Issue by QuentinRodier** [SebastienRietteMTO/PHYEX-fortran-tool#16]
The concept of tree is important and missing to handle functions that impacts the interface of a routine and then all the routines that CALL the modified routine.

WIth a concept of tree implemented, one could then resolve/develop new feature such as :
- simplify and adapt the implementation of --checkStackArginCall : it will be no needed to call this function multiple times.
- develop a new function : addVariableFromTo to add a new argument in a subroutine down in the tree and up to a upper routine in the tree (example : addVariableFromTo PTOTO sub:TURB sub:MODE_TURB_VER_THERMO_FLUX
- other ?

**Comment by SebastienRietteMTO** [comment]
Moved in https://github.com/UMR-CNRM/pyft/issues/9
