### ISSUE TITLE
USE module statement looks better and performant

### ISSUE THREAD

**Issue by QuentinRodier** [SebastienRietteMTO/PHYEX-fortran-tool#17]
USE module statements can be improved by

1. Beautifying

- packed them by type (MODE, MODI, MODD, MODN), one blank line between
- ordering by alphabetic order within a type
- upper case

2. Performing
- clean unused module
- clean unused ONLY specific variable
- [hard] : for simple 'USE MODULE' statement, detect and add 'ONLY' variables used

**Comment by SebastienRietteMTO** [comment]
Moved in https://github.com/UMR-CNRM/pyft/issues/10
