### ISSUE TITLE
Multiple nested WHERE blocks not handled

### ISSUE THREAD

**Issue by QuentinRodier** [SebastienRietteMTO/PHYEX-fortran-tool#8]
In removeArraySyntax function and expandWhereConstruct, multiple nested where are not handle in the functionnality to remove the array-syntax.
For now, only 2 double-nested WHERE are present and converted first by hand before applying the functions.

**Comment by QuentinRodier** [comment]
Add a test to check if nested WHERE is present, if found : abort pft.py

**Comment by SebastienRietteMTO** [comment]
Moved in https://github.com/UMR-CNRM/pyft/issues/2
