### ISSUE TITLE
removeIJLoops is based on the use of D, 

### ISSUE THREAD

**Issue by QuentinRodier** [SebastienRietteMTO/PHYEX-fortran-tool#9]
removeIJLoops removes DO loops on JI, JJ and JIJ.
The loop on these dimensions are placed on top parameterizations.
To loop on, D is used such as :
JIJ=D%NIJT is added in routines if dimensions on JIJ was found by removeIJLoops
(the same apply for JI or JJ and D%NIT or D%NJT)

The problem is : sometimes D is not already present in the routines, e.g. in mode_ice4_compute_pdf.F90 or mode_ice4_nucleation.F90

removeIJLoops should add it as INTENT(IN) in argument of the routines and in the routines calling these routines.

**Comment by SebastienRietteMTO** [comment]
Moved in https://github.com/UMR-CNRM/pyft/issues/3
